apiVersion: "nais.io/v1"
kind: "Naisjob"
metadata:
  name: slack-teams-notification
  namespace: nais
  labels:
    team: nais
spec:
  image: "{{ IMAGE }}"
  schedule: "0 10 11 * *"
  env:
    - name: NAIS_API_URL
      value: https://console.nav.cloud.nais.io/query
    - name: CONSOLE_FRONTEND_URL
      value: https://teams.nav.cloud.nais.io/
  envFrom:
    - secret: slack-teams-notification
  accessPolicy:
    outbound:
      external:
        - host: console.nav.cloud.nais.io
        - host: slack.com
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    team: nais
  name: slack-teams-notification
  namespace: nais
stringData:
  SLACK_API_TOKEN: "{{ SLACK_API_TOKEN }}"
  NAIS_API_TOKEN: "{{ NAIS_API_TOKEN }}"