name: Build and deploy image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      go_version: ${{ steps.go_version.outputs.go_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mise and install dependencies
        uses: jdx/mise-action@v2

      - name: Find go cache dir
        id: go-cache
        run: |
          go version
          # Clear cache dirs to avoid error when restoring
          go clean -cache -modcache
          echo "gocache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-cache.outputs.gocache }}
            ${{ steps.go-cache.outputs.gomodcache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run tests
        run: make test

      - name: Run static analysis tools
        run: make check

      - name: Find go version
        id: go_version
        run: echo "go_version=$(mise current go)" >> $GITHUB_OUTPUT

      - name: Check code format
        run: |
          make fmt
          git diff --exit-code --name-only

  build_and_push:
    needs:
      - test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build_push_sign.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: nais
          build_args: GO_VERSION=${{ needs.test.outputs.go_version }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/job.yaml
          VAR: "IMAGE=${{ steps.docker-push.outputs.image }}"
